### ISSUE TITLE
Normalization prior to clustering

### ISSUE THREAD

**Issue by corticaltone** [txWang/BERMUDA#2]
Hi
Do you normalize the data prior to clustering, or is this done using raw counts?

**Comment by txWang** [comment]
Hi,
We followed the Seurat v2 pipeline to identify cell clusters, which includes normalization before clustering. You could refer to the Seurat toolkit website (https://satijalab.org/seurat/) for more details. Thanks!

**Comment by corticaltone** [comment]
Thanks!
