### ISSUE TITLE
The data are missing

### ISSUE THREAD

**Issue by yzcv** [txWang/BERMUDA#3]
Hi,

I am quite attracted by your BERMUDA work, but I have a problem in running the "pre_processing.R" in the BERMUDA/R folder. I am wondering if you could provide the two datasets, namely "muraro_human.csv" and "baron_human.csv", which are required in the code "pre_processing.R". Thank you in advance.

**Comment by txWang** [comment]
Hi,
Sorry about that. However, the original data were too large to put here at Github. You could download the data from Gene Expression Omnibus (GSE85241 for Muraro and GSE84133 for Baron). Thank you.
